'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useContext } from 'react'
import { useRouter } from 'next/navigation'
import { AuthProvider, AuthContext } from './AuthContext'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Nav() {
  const { token, setToken } = useContext(AuthContext)
  const router = useRouter()
  const logout = () => {
    setToken(null)
    router.push('/')
  }
  return (
    <nav style={{ padding: '1rem', display: 'flex', gap: '1rem', borderBottom: '1px solid #ccc' }}>
      <a href="/">Home</a>
      {token && <a href="/dashboard">Dashboard</a>}
      {token && <a href="/connect">Connect</a>}
      {token && <a href="/plans">Plans</a>}
      {!token && <a href="/login">Login</a>}
      {!token && <a href="/register">Register</a>}
      {token && <button onClick={logout}>Logout</button>}
    </nav>
  )
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Nav />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
